### ISSUE TITLE
Wiki and social media

### ISSUE THREAD

**Issue by acra6488** [npes-95/sleeping-beauty#6]
Exciting project!
Do you have any pictures of your testing or of your boards? A social media page perhaps?
Also it would be nice to summarise your work in the Wiki pages.
-Aurelie -Team 2

**Comment by npes-95** [comment]
Hi @acra6488, we've linked our social media and relevant test videos/pictures in the README. We didn't feature them directly, as we don't want to clutter the landing page too much! 

When you say work summary, do you mean the work done so far, or a project overview?

**Comment by erikabond** [comment]
We have videos of testing on Youtube, Twitter, and also links can be found in README.
Wiki pages have been created for each of the parts of the project (hardware, GUI, RPi).
Thanks for the advice!
